---
- name: Install MicroK8s on Ubuntu
  hosts: servers
  become: yes
  tasks:
    - name: Install MicroK8s
      ansible.builtin.snap:
        name: microk8s
        classic: yes
        state: present

    - name: Add user to MicroK8s group
      ansible.builtin.user:
        name: "{{ ansible_ssh_user }}"
        groups: microk8s
        append: yes

    - name: Create .kube directory
      ansible.builtin.file:
        path: "/home/{{ ansible_ssh_user }}/.kube"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        mode: '0755'

    - name: Wait for MicroK8s to be ready
      ansible.builtin.command:
        cmd: microk8s status --wait-ready
      register: microk8s_status
      until: microk8s_status.rc == 0
      retries: 5
      delay: 10

    - name: Enable MicroK8s addons
      ansible.builtin.command:
        cmd: microk8s enable dashboard dns registry gpu
